version: '3'

services:
  iris:
    build:
      dockerfile: Dockerfile-iris
      context: '.'
    container_name: iris
    restart: always
    tty: true
    ports:
      - "52773:52773"
      - "1972:1972"
    volumes:
      - ./:/app

  dkserver:
    build:
      dockerfile: Dockerfile-dkserver
      context: '.'
    image: dkserver
    volumes:
      - .:/app