version: '3'

services:
  iris:
    build:
      dockerfile: Dockerfile-iris
      context: '.'
    container_name: iris
    restart: always
    tty: true
    ports:
      - "52773:52773"
      - "1972:1972"
    volumes:
      - .:/app
      - /var/data/iris:/irisapp:rw

  dkserver:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile-dkserver
      context: '.'
    image: dkserver
    restart: always
    tty: true
    ports:
      - "8080:80"
    links:
      - iris

  dkclient:
    env_file:
      - ../dataking-client/.env
    build:
      dockerfile: Dockerfile
      context: '../dataking-client'
    image: dkclient
    restart: always
    tty: true
    ports:
      - "8082:80"
    links:
      - dkserver