version: '3'

services:
  iris:
    build:
      dockerfile: Dockerfile-iris
      context: '.'
    container_name: iris
    restart: always
    tty: true
    ports:
      - "52773:52773"
      - "1972:1972"
    volumes:
      - .:/app

  dkserver:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile-dkserver
      context: '.'
    image: dkserver
    restart: always
    tty: true
    ports:
      - "8080:80"
    links:
      - iris
    volumes:
      - .:/app